// Motion draft generator.
// Currently returns a deterministic structured draft (no LLM required).
// To enable LLM generation in the future, set MOTION_GENERATOR_API_KEY and
// MOTION_GENERATOR_PROVIDER ("openai" | "anthropic") in your environment.

export interface MotionInputs {
  caseTitle: string;
  jurisdiction: string;
  caseType: string;
  motionType: string;
  partyRole: string;
  facts: string;
  reliefRequested: string;
  additionalContext?: string;
}

export interface GeneratedMotion {
  title: string;
  content: string;
}

export async function generateMotionDraft(
  inputs: MotionInputs
): Promise<GeneratedMotion> {
  // Future hook: if (process.env.MOTION_GENERATOR_API_KEY) return callLLM(inputs);

  const title = `${inputs.motionType} — ${inputs.caseTitle}`;

  const contextSection = inputs.additionalContext
    ? `\nAdditional Context: ${inputs.additionalContext}\n`
    : "";

  const content = `IN THE ${inputs.jurisdiction.toUpperCase()} COURT
${inputs.caseType.toUpperCase()} DIVISION

Case: ${inputs.caseTitle}
Filing Party Role: ${inputs.partyRole}

════════════════════════════════════════════════════════════
${inputs.motionType.toUpperCase()}
════════════════════════════════════════════════════════════

I. INTRODUCTION

The ${inputs.partyRole} in the above-captioned ${inputs.caseType} matter
respectfully moves this Court pursuant to applicable rules of procedure
for the relief described herein. This ${inputs.motionType} is supported by
the following facts and legal argument.

II. BACKGROUND AND STATEMENT OF FACTS

${inputs.facts}
${contextSection}
III. ARGUMENT

A. Legal Standard

[Legal standard applicable to a ${inputs.motionType} in
${inputs.jurisdiction} — to be completed by counsel based on
controlling authority.]

B. The Facts Support the Requested Relief

Based on the foregoing facts, the ${inputs.partyRole} submits that the
applicable legal standard is satisfied. [Counsel should develop this
section with specific citations to the record and controlling law.]

C. The Balance of Equities Favors the ${inputs.partyRole}

[Address any equitable considerations relevant to this motion type
under ${inputs.jurisdiction} law.]

IV. CONCLUSION AND REQUESTED RELIEF

For the foregoing reasons, the ${inputs.partyRole} respectfully requests
that this Court:

${inputs.reliefRequested}

Respectfully submitted,

_________________________________
[Attorney Name]
[Bar Number]
[Firm Name]
[Address]
[City, State, ZIP]
[Phone Number]
[Email Address]
Date: ___________________________

────────────────────────────────────────────────────────────
CERTIFICATE OF SERVICE

I hereby certify that on this date, a true and correct copy of the
foregoing ${inputs.motionType} was served upon all counsel of record via
[service method — e.g., CM/ECF, email, first-class mail].

_________________________________
[Attorney Signature]
────────────────────────────────────────────────────────────

⚠ DISCLAIMER: This document was generated by MotionForge as a
drafting aid only. It does NOT constitute legal advice, does not
create an attorney-client relationship, and must be reviewed,
completed, and modified by a licensed attorney before filing. No
case law or citations have been generated or verified. Do not
rely on this draft as legal counsel.`.trim();

  return { title, content };
}
